name: 通用配置
view:
  -
    key: 日志等级
    comment: 日志等级:trace,debug,info,warn,fatal,mark,error,off
    path: 'log_level'
    type: 'select'
    multiple: false
    item:
      -
        name: Trace
        value: trace
      -
        name: Debug
        value: ebug
      -
        name: Info
        value: info
      -
        name: Warn
        value: warn
      -
        name: Fatal
        value: fatal
      -
        name: Mark
        value: mark
      -
        name: Error
        value: error
      -
        name: Off
        value: off
  -
    key: 日志保留天数
    path: 'log_days_Keep'
    type: 'number'
  -
    key: ffmpeg路径
    comment: ffmpeg配置 用于音视频处理
    path: 'ffmpeg_path'
    type: 'text'
  -
    key: ffprobe路径
    comment: ffmpeg配置 用于音视频处理
    path: 'ffprobe_path'
    type: 'text'
  -
    key: 主人列表
    comment: 主人列表 主权限
    path: 'master'
    type: 'array'
    arrayType: 'number'
  -
    key: 管理员列表
    comment: 管理员列表 子权限
    path: 'admin'
    type: 'array'
    arrayType: 'number'
  -
    key: 黑名单
    comment: 黑名单相关
    path: 'BlackList'
    type: 'group'
    part:
        -
          key: 黑名单用户
          path: 'BlackList.users'
          type: 'array'
          arrayType: 'number'
        -
          key: 黑名单群聊
          path: 'BlackList.groups'
          type: 'array'
          arrayType: 'number'
        -
          key: 消息日志黑名单群聊
          comment: 设置后不会打印该群的消息日志
          path: 'BlackList.GroupMsgLog'
          type: 'array'
          arrayType: 'number'
  -
    key: 白名单
    comment: 白名单相关
    path: 'WhiteList'
    type: 'group'
    part:
        -
          key: 白名单用户
          path: 'WhiteList.users'
          type: 'boolean'
        -
          key: 白名单群聊
          path: 'WhiteList.groups'
          type: 'boolean'
        -
          key: 消息日志白名单群聊
          comment: 消息日志白名单群聊 设置后只会打印该群的消息日志
          path: 'WhiteList.GroupMsgLog'
          type: 'boolean'
