# 日志等级:trace,debug,info,warn,fatal,mark,error,off
log_level: info

# 日志保留天数
log_days_Keep: 7

# HTTP服务器端口
http_port: 7000

# HTTP渲染器配置
http_render:
  # 是否开启http渲染
  enable: false
  # 渲染地址 需要和karin-puppeteer的同时处于公网或者内网环境的地址
  host: http://127.0.0.1:2956
  # karin-puppeteer请求地址
  url: http://127.0.0.1:7005/api/render
  # karin-puppet请求token
  token: Karin-Puppeteer
  # 请求的非html或非有效路径的返回内容 可以填http地址 例如：https://ys.mihoyo.com
  not_found: "404 Not Found"
  # 渲染超时时间 秒
  timeout: 30

# grpc服务器地址
grpc: 0.0.0.0:7001

# 当前文件热更新是否重启http、grpc服务
hot_update: false

# 主人列表 主权限
master: []

# 管理员列表 子权限
admin: []

# 超时时间 秒
timeout:
  grpc: 30
  ws: 30

# 黑名单相关
black_list:
  # 黑名单用户
  users: []
  # 黑名单群聊
  groups: []
  # 消息日志黑名单群聊 设置后不会打印该群的消息日志
  msg_groups: []

# 白名单相关
white_list:
  # 白名单用户
  users: []
  # 白名单群聊
  groups: []
  # 消息日志白名单群聊 设置后只会打印该群的消息日志
  msg_groups: []

# ffmpeg配置 用于音视频处理
ffmpeg_path: ""
ffprobe_path: ""
