# 日志等级:trace,debug,info,warn,fatal,mark,error,off
log_level: info

# 日志保留天数
log_days_Keep: 7

# 控制台触发插件日志颜色 十六进制 默认#FFFF00 不支持热更新
log_color: "#E1D919"

# ffmpeg配置 用于音视频处理
ffmpeg_path: ""
ffprobe_path: ""

# 主人列表 主权限
master: []

# 管理员列表 子权限
admin: []

# 黑名单相关
BlackList:
  # 黑名单用户
  users: []
  # 黑名单群聊
  groups: []
  # 消息日志黑名单群聊 设置后不会打印该群的消息日志
  GroupMsgLog: []

# 白名单相关
WhiteList:
  # 白名单用户
  users: []
  # 白名单群聊
  groups: []
  # 消息日志白名单群聊 设置后只会打印该群的消息日志
  GroupMsgLog: []
