# log4js 日志配置
log4jsCfg:
  # 日志等级: trace, debug, info, warn, fatal, mark, error, off
  level: info
  # 日志保留天数
  daysToKeep: 7
  # 整体化: 将日志输出到一个文件(一天为一个文件) 日志较多的情况下不建议与碎片化同时开启
  overall: true
  # 碎片化: 将日志分片，达到指定大小后自动切割 日志较多的情况下不建议与整体化同时开启
  fragments: false
  # 日志文件最大大小 MB
  maxLogSize: 30

# 控制台触发插件日志颜色 十六进制 默认#FFFF00 不支持热更新
log_color: "#E1D919"

# 重启是否调用pm2 如果不调用则会直接关机 此配置适合有进程守护的程序
pm2Restart: true

# 私聊设置
private:
  # 关闭私聊后回复的提示词 为空则不回复
  tips: ""
  # 关闭私聊后的用户白名单
  white_list: []

# input适配器配置 以下所有配置均不支持热更新
AdapterInput:
  # 是否启用
  enable: true
  # 是否将语音、图片、视频消息转为文件 转为文件后可通过url访问
  msgToFile: true
  # url访问token 如果为 AdapterInput 每次启动后会重新生成
  token: "AdapterInput"
  # 访问ip
  ip: 127.0.0.1

# ffmpeg配置 用于音视频处理
ffmpeg_path:
ffprobe_path:

# 主人列表 主权限
master:
  - input

# 管理员列表 子权限
admin: []

# 黑名单相关
BlackList:
  # 黑名单用户
  users: []
  # 黑名单群聊
  groups: []
  # 消息日志黑名单群聊 设置后不会打印该群的消息日志
  GroupMsgLog: []

# 白名单相关
WhiteList:
  # 白名单用户
  users: []
  # 白名单群聊
  groups: []
  # 消息日志白名单群聊 设置后只会打印该群的消息日志
  GroupMsgLog: []
