# chromium 地址，可填写系统的edge/chromium路径，例如（根据实际情况调整）：
# chromiumPath: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
chromiumPath:

# puppeteer websocket 地址。连接单独存在的 chromium。
# puppeteerWS: 'ws://browserless:3000'
puppeteerWS:

# headless 模式，可选值：true/false/new/shell 关闭无头/开启无头/新无头/旧无头
headless: "shell"

# puppeteer启动args，注意args的--前缀
args:
  - --disable-gpu
  - --disable-setuid-sandbox
  - --no-sandbox
  - --no-zygote

# puppeteer截图超时时间
puppeteerTimeout:

# redis-key
redisKey: "puppeteer:chromium"

# 创建页面到达多少重启 chromium
createPageCount: 100

# 页面超时时间 默认5秒
timeout: 5000